[toolchain]
anchor_version = "0.29.0"

[test]
startup_wait = 15000

[features]
seeds = false
skip-lint = false

[programs.devnet]
ali_pump_fun = "3gfMvGB7L2TrBw8CwaRzKZ9KySKrh4cFG23ZUFKoBN99"
pump_fun = "MXtLoTxTTYs9dQJVc9p5m4RoBoNBgLtDfRATXAerPs7"

[programs.localnet]
ali_pump_fun = "3gfMvGB7L2TrBw8CwaRzKZ9KySKrh4cFG23ZUFKoBN99"
pump_fun = "MXtLoTxTTYs9dQJVc9p5m4RoBoNBgLtDfRATXAerPs7"

[programs.mainnet]
ali_pump_fun = "3gfMvGB7L2TrBw8CwaRzKZ9KySKrh4cFG23ZUFKoBN99"
pump_fun = "MXtLoTxTTYs9dQJVc9p5m4RoBoNBgLtDfRATXAerPs7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "p_key_solana"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pump_fun.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/ali_pump_fun.ts"